apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "netomedia.fullname" . }}
  labels:
    {{- include "netomedia.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "netomedia.fullname" . }}
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20