apiVersion: v1
kind: Service
metadata:
  name: {{ include "netomedia.fullname" . }}
  labels:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: {{ include "netomedia.fullname" . }}
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
